import { copyToClipboard, escHtml } from './js/utils.js';
window.copyToClipboard = copyToClipboard;
window.escHtml = escHtml;

import './js/core/navigation.js';
import './js/core/shortcuts.js';
import './js/core/favorites.js';
import './js/core/theme.js';
import './js/tools/base64.js';
import './js/tools/hash.js';
import './js/tools/epoch.js';
import './js/tools/json.js';
import './js/tools/jwt.js';
import './js/tools/color.js';
import './js/tools/uuid.js';
import './js/tools/qr.js';
import './js/tools/regex.js';
import './js/tools/diff.js';
import './js/tools/base.js';
import './js/tools/lorem.js';
import './js/tools/string.js';
import './js/tools/password.js';
import './js/tools/markdown.js';
import './js/tools/unit.js';
